import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Food Wagon",
  description: "Generated by create next app",
  icons:"images/icons/iconLogo.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
